<?php

namespace BackEndBundle\Repository;

/**
 * MissionReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionReportRepository extends \Doctrine\ORM\EntityRepository
{
}
