<?php

namespace BackEndBundle\Repository;

/**
 * TravelPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
